zachsaw/MPDN_Extensions

Extensions/PlayerExtensions/RemoteControl.cs, Extensions/PlayerExtensions/RemoteControlConfig.Designer.cs, Extensions/PlayerExtensions/RemoteControlConfig.cs, Extensions/PlayerExtensions/RemoteControl_AuthHandler.cs
I've added the ability to disable remote auth requirement, moved the auth save details to the %appdata% folder and added method to allow switching audio channels.
=> Multiple fixes

Extensions/PlayerExtensions/PlaylistForm.cs
Fixed the following oversight:
* Playlist going out of screen bounds when window is too large
To do:
* ~~Show the playlist above the player when it set to always on top~~
=> Playlist fixes

Extensions/PlayerExtensions/Playlist.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.Designer.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.cs, Extensions/PlayerExtensions/PlaylistForm.Designer.cs, Extensions/PlayerExtensions/PlaylistForm.cs
Had this done for a while but it needed a little more testing. 
Summarizing it a bit, the following are added/changed:
- added a context menu with the basic operations
- added a minimum size for the chapter columns
- restyled the playlist buttons
- added the ability to remove the current playing file
- added remembering window size and position
- add any opened file (in any way) to the playlist
- added remember previous played file and add it to playlist
- added settings dialog
Some things that need to get looked at though are the reordering with drag and drop. Need to figure out a way to make it less annoying when (auto)scrolling back.
Test and review please.
=> Implemented a bunch of requests

Extensions/PlayerExtensions/Playlist.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.Designer.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.cs, Extensions/PlayerExtensions/PlaylistForm.Designer.cs, Extensions/PlayerExtensions/PlaylistForm.cs, Extensions/PlayerExtensions/Resources/Mpdn.PlayerExtensions.Playlist.PlaylistForm.resx, Sources/PlayerExtensions/PlaylistForm.resx
Added the following:
- Added a button to change the settings via the playlist
- Added the option to make the playlist visible on startup
- Added the option to automatically play a file when opening it
=> Implemented more requests

Extensions/PlayerExtensions/MbtBridge.cs, Extensions/PlayerExtensions/RemoteControl.cs
Adds a new MbtBridge extension which assists with the interop between MBT and MPDN.
Also a few bug fixes for the remote control extension.
=> Media Browser Theater Bridge

Extensions/Framework/Filter.cs, Extensions/Framework/RenderChainScript.cs, Extensions/RenderScripts/Shiandow.Nedi.NediScaler.cs, Extensions/RenderScripts/Shiandow.Nnedi3.Scaler.cs, Extensions/RenderScripts/Shiandow.SuperRes.ConfigDialog.Designer.cs, Extensions/RenderScripts/Shiandow.SuperRes.ConfigDialog.cs, Extensions/RenderScripts/Shiandow.SuperRes.cs
Also removed some bugs I found along the way. It's now easier (and far less buggy) to optimize filters away.
=> Make SuperRes prescalers configureable

Extensions/PlayerExtensions/OpenSubtitles.ConfigDialog.cs, Extensions/PlayerExtensions/OpenSubtitles.ConfigDialog.designer.cs, Extensions/PlayerExtensions/OpenSubtitles.Downloader.cs, Extensions/PlayerExtensions/OpenSubtitles.PlayerExtension.cs, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.Designer.cs, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.cs
Hi Zach,
Here is the first version after merging with your change done by email.
Regards
=> [ADD] Adding Support to OpenSubtitles

Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.Designer.cs, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.cs
Disabling multi-select in the code
=> [FIX] Removing resx have reenabled the MutliSelect.

Extensions/PlayerExtensions/OpenSubtitles.ConfigDialog.cs, Extensions/PlayerExtensions/OpenSubtitles.ConfigDialog.designer.cs, Extensions/PlayerExtensions/OpenSubtitles.PlayerExtension.cs, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.cs
If the preferred language is not available, it will shows all the langauges
=> Add possibility to set a preferred language for OpenSubtitles

Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.Designer.cs, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.cs
Usual behaviour expected from an UI
=> Double click on row download the subtitle

Extensions/Framework/Filter.Sources.cs, Extensions/Framework/Filter.Text.cs, Extensions/Framework/Filter.cs, Extensions/Framework/RenderChain.cs, Extensions/Framework/RenderChainScript.cs, Extensions/RenderScripts/Mpdn.Lut3D.cs, Extensions/RenderScripts/Mpdn.OclNnedi3.Nnedi3Scaler.cs, Extensions/RenderScripts/Mpdn.Presets.cs
Fixes issues with Script Chain.
=> Partially revert changes to IFilter

Extensions/PlayerExtensions/UpdateChecker.PlayerExtension.cs
Set the header before each request
=> Add manual way to check for Update

Extensions/PlayerExtensions/UpdateChecker.PlayerExtension.cs
Use it for the User-Agent and later on for the Extension Checker.
=> [MOD] Retrieve the extension version from assembly

Extensions/PlayerExtensions/OpenSubtitles.ConfigDialog.cs, Extensions/PlayerExtensions/OpenSubtitles.ConfigDialog.designer.cs, Extensions/PlayerExtensions/OpenSubtitles.LanguageHandler.cs, Extensions/PlayerExtensions/OpenSubtitles.PlayerExtension.cs, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.Designer.cs, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.cs, Mpdn.Extensions.csproj
This way the user can easily change the language without the need to change the preferred one.
=> Add Filter ComboBox for OpenSubtitles

.gitignore, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.Designer.cs, Extensions/PlayerExtensions/OpenSubtitles.Subtitles.Form.cs, MPDN/.gitignore
Before it wasn't possible to select another language using the scrolling.
=> OpenSubtitles: Scrolling can be used to select language

Extensions/PlayerExtensions/UpdateChecker.ExtensionAvailable.Form.Designer.cs, Extensions/PlayerExtensions/UpdateChecker.ExtensionAvailable.Form.cs, Extensions/PlayerExtensions/UpdateChecker.WebFile.cs, Mpdn.Extensions.csproj
Can be later used also for the UpdateChecker of the player. But I would like some feedback on this code before doing the same for the Player.
=> Adding a FileDownloader for Extensions

Extensions/PlayerExtensions/Playlist.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.Designer.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.cs, Extensions/PlayerExtensions/PlaylistForm.Designer.cs, Extensions/PlayerExtensions/PlaylistForm.cs
More fixes and changes. See commit messages for more info.
=> Playlist fixes and changes

Extensions/PlayerExtensions/GoToTimeForm.Designer.cs, Extensions/PlayerExtensions/GoToTimeForm.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.Designer.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.cs, Extensions/PlayerExtensions/ViewMediaInfoForm.Designer.cs, Extensions/PlayerExtensions/ViewMediaInfoForm.cs
One playlist commit snuck in, but what the heck.
Playlist:
- Refactoring and prevent regex window from closing settings
- Changed the behavior of the "Close" button to also save the
changes in addition to closing
- Removed "apply" button and added a "clear" button instead for
convenience
GoToTime
- Added set current media position & minor cosmetic changes for GoToTime
MediaInfo
- Style up MediaInfo dialog and added MPDN icon
=> Extension enhancements

Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.UpdateAvailable.Form.Designer.cs, Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.UpdateAvailable.Form.cs
UpdateChecker: Make the Form bigger to have a better display of the changelog
=> UpdateChecker: Follow advice of @Garteal. See #74

Extensions/PlayerExtensions/Exceptions/Exceptions.cs, Extensions/PlayerExtensions/Subtitles/OpenSubtitles.PlayerExtension.cs, Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.PlayerExtension.cs, Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.UpdateAvailable.Form.cs, Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.Version.cs
Processing correctly the lack of internet connection when doing an UpdateCheck.
=> Updatechecker: Checking for internet connection

Installer/Installer.nsi
Installer: Change the title and message to reflect the installation of the player
Installer: Make the Download/Update Section visible but mandatory when updating the player
See #115
=> Installer: Download the latest version of the player

Extensions/PlayerExtensions/UpdateChecker/SimpleUpdateForm.Designer.cs, Extensions/PlayerExtensions/UpdateChecker/SimpleUpdateForm.cs
UpdateChecker: Make the simple update form appears in the center of the parent form.
See #128
=> UpdateChecker: Correct a possible NPE if no file is being downloaded.

Extensions/PlayerExtensions/UpdateChecker/SimpleUpdateForm.cs
It also make the download stop if it was launched.
Fixes #131
=> UpdateChecker: Make the forget button close the Form

Extensions/PlayerExtensions/UpdateChecker/ChangelogWebViewer.cs, Extensions/PlayerExtensions/UpdateChecker/Helpers.cs, Extensions/PlayerExtensions/UpdateChecker/SimpleUpdate.ChangelogForm.Designer.cs, Extensions/PlayerExtensions/UpdateChecker/SimpleUpdate.ChangelogForm.cs, Extensions/PlayerExtensions/UpdateChecker/SimpleUpdateForm.Designer.cs, Extensions/PlayerExtensions/UpdateChecker/SimpleUpdateForm.cs, Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.UpdateAvailable.Form.Designer.cs, Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.UpdateAvailable.Form.cs, Mpdn.Extensions.csproj
The biggest change is the addition of the new version in the SimpleUpdateChecker + the possibility to see the changelog (clickable link the the SimpleUpdateChecker).
=> UpdateChecker: Changelog for SimpleUpdateChecker

Extensions/PlayerExtensions/UpdateChecker/SimpleUpdate.ChangelogForm.Designer.cs, Extensions/PlayerExtensions/UpdateChecker/SimpleUpdate.ChangelogForm.cs, Extensions/PlayerExtensions/UpdateChecker/SimpleUpdateForm.Designer.cs
Make the SimpleUpdate Form bigger (trying to clear the issue with UI at 150%).
Make the text of the ChangelogForm reflecting the changelog displayed.
=> UpdateChecker: Change the UI.

Extensions/PlayerExtensions/Images/Playlist/properties.txt, Extensions/PlayerExtensions/Playlist.cs, Extensions/PlayerExtensions/PlaylistForm.Designer.cs, Extensions/PlayerExtensions/PlaylistForm.cs
- Makes the Playlist respond to closing a file with CTRL+C in MPDN again (don't even remember removing it)
- Add more theming options
- Fix OS detection and snapping
=> Playlist features

Extensions/Framework/Controls/RenderChainList.Designer.cs, Extensions/RenderScripts/Deband/Deband.hlsl, Extensions/RenderScripts/Shiandow.SuperChromaRes.cs, Extensions/RenderScripts/Shiandow.SuperRes.cs, Extensions/RenderScripts/SuperRes/Diff.hlsl, Extensions/RenderScripts/SuperRes/SuperChromaRes/SuperResEx.hlsl, Extensions/RenderScripts/SuperRes/SuperResEx.hlsl
Most changes won't be too visible. Only the change to SuperRes are somewhat noticeable.
This may or may not fix #138.
=> Various tweaks

Extensions/Framework/RenderChain/Filter.Chroma.cs, Extensions/Framework/RenderChain/Filter.Utilities.cs, Extensions/Framework/RenderChain/RenderChainScript.cs, Extensions/PlayerExtensions/Navigation.cs, Extensions/RenderScripts/Common/MergeY_UV.hlsl, Extensions/RenderScripts/Mpdn.EwaChromaScaler.cs, Extensions/RenderScripts/Shiandow.Chroma.ChromaScaler.cs, Extensions/RenderScripts/Shiandow.Nnedi3.Scaler.cs, Extensions/RenderScripts/Shiandow.SuperChromaRes.cs, Extensions/RenderScripts/SuperRes/SuperChromaRes/CrossBilateral.hlsl, Extensions/RenderScripts/SuperRes/SuperChromaRes/Diff.hlsl, Mpdn.Extensions.Framework.csproj
Also includes an unrelated change to "Navigation.cs"
=> Rework Chroma Scaling

Extensions/Framework/Controls/ChromaScalerSelector.cs, Extensions/Framework/RenderChain/Filter.Chroma.cs, Extensions/Framework/RenderChain/Filter.Sources.cs, Extensions/Framework/RenderChain/Filter.cs, Extensions/Framework/RenderChain/Presets.cs, Extensions/Framework/RenderChain/RenderChainScript.cs, Extensions/RenderScripts/Mpdn.EwaChromaScaler.cs, Extensions/RenderScripts/Mpdn.OclNnedi3.Chroma.Nnedi3Scaler.cs, Extensions/RenderScripts/Shiandow.Chroma.ChromaScaler.cs, Extensions/RenderScripts/Shiandow.Nnedi3.Chroma.Scaler.cs, Extensions/RenderScripts/Shiandow.SuperChromaRes.cs
This should fix a lot of problems with 'uncommon' chroma/luma sizes.
=> More chroma scaling improvements

Extensions/Framework/RenderChain/Filter.Chroma.cs, Extensions/RenderScripts/Shiandow.SuperRes.cs
Forgot to optimize ChromaFilter's output. 
Possibly related to #152.
=> Small fixes

Extensions/Framework/RenderChain/Filter.Chroma.cs, Extensions/Framework/RenderChain/Filter.Sources.cs, Extensions/Framework/RenderChain/Filter.Utilities.cs, Extensions/Framework/RenderChain/RenderChain.cs, Extensions/Framework/RenderChain/RenderChainScript.cs, Extensions/RenderScripts/Mpdn.EwaChromaScaler.cs, Extensions/RenderScripts/Mpdn.OclNnedi3.Chroma.Nnedi3Scaler.cs, Extensions/RenderScripts/Shiandow.Chroma.ChromaScaler.cs, Extensions/RenderScripts/Shiandow.Nnedi3.Chroma.Scaler.cs, Extensions/RenderScripts/Shiandow.Nnedi3.Scaler.cs, Extensions/RenderScripts/Shiandow.SuperChromaRes.cs
An alternative way of implementing the last 3 commits.
=> Rework changes to Framework

Extensions/PlayerExtensions/ViewMediaInfoForm.cs
Needs a revert because case sensitivity matters.
=> Revert changes to MediaInfo

Extensions/PlayerExtensions/Images/Playlist/Default/theme.style, Extensions/PlayerExtensions/Playlist.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.Designer.cs, Extensions/PlayerExtensions/PlaylistConfigDialog.cs, Extensions/PlayerExtensions/PlaylistForm.Designer.cs, Extensions/PlayerExtensions/PlaylistForm.cs, Mpdn.Extensions.csproj
You've got some features in here I've been waiting for so if it's okay with you I'd like to merge it.
=> [Playlist] Add support for URLs in playlist and docking location

Extensions/AudioScripts/Mpdn.DynamicRangeCompressor.cs, Extensions/AudioScripts/Mpdn.Reclock.cs, Extensions/Framework/AudioChain/AudioChainUi.cs
=> [Framework] Make AudioChainUi inherit from ChainUi

Extensions/PlayerExtensions/PlaylistForm.cs
=> Fixup PlayNextFileInDirectory preloading

Extensions/PlayerExtensions/RemoteControl.cs, Mpdn.Extensions.sln
Fixed issue where remote couldn't talk to MPDN after initial auth requiring reconnect before working.
=> Fixed issue during initial auth

Extensions/Framework/Filter/Filter.Sources.cs, Extensions/Framework/Filter/Filter.cs, Extensions/Framework/RenderChain/Filter.Sources.cs, Extensions/Framework/RenderChain/TextureFilter.Sources.cs, Extensions/Framework/RenderChain/TextureFilter.Text.cs, Extensions/Framework/RenderChain/TextureFilter.Utilities.cs, Extensions/Framework/RenderChain/TextureFilter.cs, Extensions/Framework/RenderChain/Textures.cs, Extensions/RenderScripts/Bilateral/CrossBilateral.hlsl, Extensions/RenderScripts/Deband/Deband.hlsl, Extensions/RenderScripts/Shiandow.SuperChromaRes.cs, Extensions/RenderScripts/Shiandow.SuperRes.cs, Extensions/RenderScripts/SuperRes/SuperChromaRes/Diff.hlsl, Extensions/RenderScripts/SuperRes/SuperChromaRes/SuperResEx.hlsl, Extensions/RenderScripts/SuperRes/SuperResEx.hlsl
TODO: Manage the InputRenderTarget texture.
=> [Framework] Changes to VideoSourceFilter

Extensions/Framework/Chain/Chain.cs, Extensions/Framework/Chain/Preset.cs, Extensions/Framework/Chain/PresetCollections.cs, Extensions/Framework/Hotkeys.cs, Mpdn.Extensions.Framework.csproj
Also fix some minor issues that made ScriptGroup hotkeys slower than necessary.
Switching renderscripts is still a bit sluggish though. Not sure why.
=> [WIP] Remove "Chain.Intialize()" and "Chain.Reset()"

Extensions/Framework/RenderChain/RenderChain.cs, Extensions/RenderScripts/Mpdn.OclNnedi3.Chroma.Nnedi3Scaler.cs, Extensions/RenderScripts/Mpdn.OclNnedi3.Nnedi3Scaler.cs, Extensions/RenderScripts/SSimDownscaler/Calc.hlsl, Extensions/RenderScripts/SSimDownscaler/SoftDownscaler.hlsl, Extensions/RenderScripts/Shiandow.Nnedi3.Filters.cs, Extensions/RenderScripts/Shiandow.SSimDownscaling.ConfigDialog.Designer.cs, Extensions/RenderScripts/Shiandow.SSimDownscaling.ConfigDialog.cs, Extensions/RenderScripts/Shiandow.SSimDownscaling.cs, Mpdn.Extensions.csproj
Note: made some small(ish) additional changes to the framework to allow the following syntax:
var Calc = CompileShader("calc.hlsl");
Calc["strength"] = Strength;
Which is quite nice.
=> Add SSIM config dialog

Extensions/Framework/RenderChain/RenderChainScript.cs, Extensions/RenderScripts/Bilateral/CrossBilateral.hlsl, Extensions/RenderScripts/Shiandow.Bilateral.ConfigDialog.Designer.cs, Extensions/RenderScripts/Shiandow.Bilateral.ConfigDialog.cs, Extensions/RenderScripts/Shiandow.Bilateral.cs, Mpdn.Extensions.csproj
I've manage to lower the artefacts enough to make it suited for general use (probably).
Now it just needs to be tested.
Also fixed a small issue with the VideoSourceFilter (preventing some unnecessary conversions).
=> Finalize Reconstructive Bilateral

Extensions/Framework/Filter/Filter.Tag.cs, Extensions/Framework/RenderChain/TextureFilter/Sources.cs, Extensions/RenderScripts/Bilateral/CrossBilateral.hlsl, Extensions/RenderScripts/SuperRes/SuperChromaRes/SuperRes.hlsl
=> RGB conversion bugfix

Extensions/Framework/Filter/Filter.Tag.cs, Extensions/Framework/Filter/Filter.cs, Extensions/Framework/RenderChain/TextureFilter/Sources.cs, Extensions/RenderScripts/Bilateral/CrossBilateral.hlsl, Extensions/RenderScripts/SSSR/Diff.hlsl, Extensions/RenderScripts/SSSR/Downscale.hlsl, Extensions/RenderScripts/SSSR/DownscaleII.hlsl, Extensions/RenderScripts/SSSR/GammaToLinear.hlsl, Extensions/RenderScripts/SSSR/SuperRes.hlsl, Extensions/RenderScripts/Shiandow.SSSR.ConfigDialog.Designer.cs, Extensions/RenderScripts/Shiandow.SSSR.ConfigDialog.cs, Extensions/RenderScripts/Shiandow.SSSR.cs, Extensions/RenderScripts/Shiandow.SuperRes.cs, Mpdn.Extensions.csproj
SSSR = Structural Similarity (SSIM) SuperRes
Also improved (fixed) SuperRes defaults, and changed tweaked Bilateral slightly.
=> New SuperRes-based Upscaler: SSSR

Extensions/RenderScripts/SSSR/SuperRes.hlsl, Extensions/RenderScripts/Shiandow.SSSR.cs
Hybrid mode combines the sharp and soft modes to accelerate convergence.
=> SSSR: Improved quality, New 'hyrbid' mode.

Extensions/Framework/RenderChain/TextureFilter/Interface.cs, Extensions/PlayerExtensions/DynamicHotkeys.cs, Extensions/RenderScripts/Bilateral/CrossBilateral.hlsl, Extensions/RenderScripts/SSSR/SuperRes.hlsl, Extensions/RenderScripts/Shiandow.Bilateral.ConfigDialog.Designer.cs, Extensions/RenderScripts/Shiandow.Bilateral.ConfigDialog.cs, Extensions/RenderScripts/Shiandow.Bilateral.cs, Extensions/RenderScripts/Shiandow.SSSR.ConfigDialog.Designer.cs, Extensions/RenderScripts/Shiandow.SSSR.ConfigDialog.cs, Extensions/RenderScripts/Shiandow.SSSR.cs
=> Bilateral and SSSR update

Extensions/Framework/Controls/ChainList.cs, Extensions/Framework/Helpers.cs, Extensions/RenderScripts/Mpdn.Conditional.cs
This probably works, but it's late, so I'm going to give it another look tomorrow.
=> [Fix] Conditional's settings dialog failed to load settings
