- Extensions/RenderScripts/Shiandow.Deband.cs
Setting the margin to 1.0 removes too much detail, the value 0.25 seems to be high enough to still remove banding.
> Lower margin to 0.25

- Extensions/PlayerExtensions/UpdateChecker.ConfigDialog.cs
- Extensions/PlayerExtensions/UpdateChecker.ConfigDialog.designer.cs
- Extensions/PlayerExtensions/UpdateChecker.PlayerExtension.cs
- Extensions/PlayerExtensions/UpdateChecker.UpdateAvailable.Form.Designer.cs
- Extensions/PlayerExtensions/UpdateChecker.UpdateAvailable.Form.cs
Check for new version Async at launch of the player
Let the user decide if they want to download it or forget the new version
Can be disabled in the configuration or by keyboard shortcut
> Adding the UpdateChecker

- Installer.nsi
Giving the mutex a name to avoid conflict with other installer using the default name in the tutorial
> Fixing the Mutex in the installer

- Installer/Installer.nsi
- Installer/Make-Installer.bat
Minor changes to reduce the size of the uninstaller (and installer) by removing the use of 2 set of instruction for X64 and X86.
The files are the same for both version, using only one set of instruction with a Directory variable set before processing the uninstall instructions.
> Some Cleanup of the Uninstall process

- Extensions/Framework/Helpers.cs
- Extensions/Framework/RenderChain/Presets.cs
- Extensions/Framework/RenderChain/RenderChain.cs
- Extensions/Framework/RenderChain/RenderChainScript.cs
- Extensions/RenderScripts/Common/ColourProcessing.hlsl
- Extensions/RenderScripts/Deband/Deband.hlsl
- Extensions/RenderScripts/Mpdn.ScriptChain.cs
- Extensions/RenderScripts/Mpdn.ScriptGroup.cs
- Extensions/RenderScripts/Shiandow.Deband.ConfigDialog.Designer.cs
- Extensions/RenderScripts/Shiandow.Deband.ConfigDialog.cs
- Extensions/RenderScripts/Shiandow.SuperChromaRes.cs
- Extensions/RenderScripts/Shiandow.SuperRes.cs
- Extensions/RenderScripts/SuperRes/Diff.hlsl
- Extensions/RenderScripts/SuperRes/SuperChromaRes/SuperResEx.hlsl
- Extensions/RenderScripts/SuperRes/SuperResEx.hlsl
The error handling is now done by the RenderChainScript. This prevents renderscripts like SuperRes from making the error message unreadable. Moving the responsibility to RenderChainScript also means that RenderChains don't have to do any error-handling themselves, removing the need for "CreateSafeFilter".
The debanding shader has been modified a bit in another attempt to distinguish better between detail and banding.
The colour conversions of SuperRes have been optimized, it no longer uses L*a*b (although doing so wouldn't have too big an impact on performance). Also disabled softness, it didn't work well enough. I'm still planning to do something with the setting (not sure what though) so I'll leave it in the dialog for now.
Also added a (very) minor optimization for SuperChromaRes.
> Change Error Handling, Improve Debanding, Optimize SuperRes

- Extensions/PlayerExtensions/Subtitles/SubtitleDragAndDrop.cs
- Extensions/PlayerExtensions/Subtitles/SubtitleManager.cs
- Mpdn.Extensions.csproj
With this new extension the user can Drag and Drop subtitle file in MPDN, the player will detect them as Subtitle and load them using the COM Interface.
If multiple subtitle are dropped only the first one is loaded.
> Subtitle: Add support for Drag and Drop

- Extensions/Framework/Config/ExtensionsUi.cs
- Extensions/Framework/Config/ScriptSettingsBase.cs
- Extensions/Framework/Controls/RenderChainList.Designer.cs
- Extensions/Framework/Controls/RenderChainList.cs
- Extensions/Framework/Helpers.cs
- Extensions/PlayerExtensions/Subtitles/SubtitleDragAndDrop.cs
- Extensions/RenderScripts/Mpdn.ScriptGroup.cs
Added several ways to use the Config framework to convert objects to and from strings. Consisting of one general "ConfigHelper" and some functions specific to ExtensionUis.
Extended RenderChainList to use these functions for copy / pasting renderscripts. This way you can paste and copy renderscripts as text.
Also fixed some bugs.
> String conversions and Copy/Paste-ing

- Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.PlayerExtension.cs
- Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.Version.cs
The updatechecker now check for API version to avoid installing update that would break compatibility.
> Updatechecker: Implements #144

- Extensions/Framework/RenderChain/Filter.Chroma.cs
- Extensions/Framework/RenderChain/Filter.Sources.cs
- Extensions/Framework/RenderChain/Filter.Utilities.cs
- Extensions/Framework/RenderChain/Filter.cs
- Extensions/Framework/RenderChain/Presets.cs
- Extensions/Framework/RenderChain/RenderChain.cs
- Extensions/RenderScripts/Mpdn.EwaChromaScaler.cs
- Extensions/RenderScripts/Mpdn.OclNnedi3.Chroma.Nnedi3Scaler.cs
- Extensions/RenderScripts/Mpdn.ScriptGroup.cs
- Extensions/RenderScripts/Shiandow.Chroma.ChromaScaler.cs
- Extensions/RenderScripts/Shiandow.Nnedi3.Chroma.Scaler.cs
- Extensions/RenderScripts/Shiandow.SuperChromaRes.cs
- Extensions/RenderScripts/Shiandow.SuperRes.cs
Some refactoring to make statuses easier to handle, and improve them were necessary.
Chroma scalers now report when the Luma is scaled.
Also report when scaling happens after the chroma scaling (e.g. when using SuperChromaRes while downscaling).
These two situations look *and are* different.
> More status improvements

- Extensions/Framework/Helpers.cs
- Extensions/Framework/RenderChain/Filter.Chroma.cs
- Extensions/Framework/RenderChain/Filter.Sources.cs
- Extensions/Framework/RenderChain/Filter.Utilities.cs
- Extensions/Framework/RenderChain/Filter.cs
- Extensions/Framework/RenderChain/RenderChain.cs
- Extensions/Framework/RenderChain/RenderChainScript.cs
- Extensions/Framework/RenderChain/RenderChainUi.cs
- Extensions/PlayerExtensions/ScriptChainOsdPainter.cs
- Extensions/RenderScripts/Bilateral/CrossBilateral.hlsl
- Extensions/RenderScripts/Mpdn.EwaChromaScaler.cs
- Extensions/RenderScripts/Mpdn.OclNnedi3.Nnedi3Scaler.cs
- Extensions/RenderScripts/Shiandow.Bilateral.cs
- Extensions/RenderScripts/Shiandow.Chroma.ChromaScaler.cs
- Extensions/RenderScripts/Shiandow.Nnedi3.Scaler.cs
- Extensions/RenderScripts/Shiandow.SuperChromaRes.cs
- Extensions/RenderScripts/Shiandow.SuperRes.cs
- Mpdn.Extensions.csproj
Also move the Bilateral chroma scaler to it's own render script.
Filters now automatically append post-resize information (if any). To make this feasible I needed to add a "Mentioned" switch to the Resize Filters, otherwise it was almost impossible to prevent a resize step from being mentioned more than once.
This switch could probably be implemented in a better way though.
> More Status Stuff

- Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.PlayerExtension.cs
- Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.Version.cs
Use JSON instead of text to provide update information for the player. 
http://mpdn.zachsaw.com/LatestVersion.json
Old URL still available and working as before for retrocompatibility.
http://mpdn.zachsaw.com/LatestVersion.txt
> Updatechecker: fixes #164 and use JSON instead of Text

- README.md
The wiki home page had been renamed to make it the 'default' wiki page (which is apparently only possible by changing the title to "home").
> [Readme] update wiki url

- Extensions/PlayerExtensions/Playlist.cs
- Extensions/PlayerExtensions/PlaylistForm.cs
Small fixup.
Fixes crashing when trying to load the next file in directory if we're playing an URL.
> [Playlist] Don't try to play the next in directory if the file doesn't exist

- Extensions/Framework/RenderChain/Filter.cs
- Extensions/Framework/RenderChain/RenderChainScript.cs
InputFilters was null
RenderChainScript error handling would throw errors
Previous pull request should work, now (at least, it played back videos).
> [Fix] Disposing Filters took exponential time, and 2 other bugs

- Extensions/PlayerExtensions/PlaylistForm.cs
Remove extra NotifyPlaylistChanged event from Playlist (already called in Populatelaylist) that causes remote to receive multiple playlist changed events when rearranging the playlist.
This causes the remote to sometime show too many copies of a file as it is trying to do rearrangements while also trying to handle the next request.
> Remove extra NotifyPlaylistChanged event from Playlist

- Extensions/PlayerExtensions/UpdateChecker/UpdateChecker.PlayerExtension.cs
I'm using [let's encrypt](https://letsencrypt.org/) to automatically generate and update certificate for most of my website. I applied the same for MPDN.
> Change HTTP to HTTPS for the UpdateChecker MPDN repo

- Extensions/RenderScripts/SSimDownscaler/CalcD.hlsl
- Extensions/RenderScripts/SSimDownscaler/CalcR.hlsl
- Extensions/RenderScripts/SSimDownscaler/CalcT.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/ConvolvedVar_H.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/ConvolvedVar_V.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/Convolver.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/DownscaledVar_H.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/DownscaledVar_V.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/Downscaler.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/Upscaler.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/Var_H.hlsl
- Extensions/RenderScripts/SSimDownscaler/Scalers/Var_V.hlsl
- Extensions/RenderScripts/Shiandow.SSimDownscaling.cs
- Mpdn.Extensions.csproj
My code is somewhat tied up in the changes to the framework, some traces of which can be found in this code (mainly the change "new ShaderFilter(shader" => "shader.ApplyTo("). And it could take a while before the 'filter' branch is stable, so I made this separate branch to push some changes to.
Anyway, without further ado: here is the new SSIM based downscaler.
I'd appreciate it if someone could check if this actually compiles.
> Add SSIM downscaler

- Extensions/Framework/RenderChain/TextureFilter/Chroma.cs
- Extensions/Framework/RenderChain/TextureFilter/Interface.cs
Chroma scaler failed, calling "SetSize' on the fallback would make an
identical chroma scaler, which would also fail etc.
To prevent this fallback should only be changed manually, when
appropriate.
> [Fix] Stack overflow on failed chromascaler resize.

- Extensions/Framework/RenderChain/TextureFilter/Chroma.cs
Tag system keeps creating problems, might be better to replace it entirely.
> [Fix] Stack overflow caused by circular tag reference.

- Extensions/PlayerExtensions/OnScreenDisplay.cs
- Mpdn.Extensions.csproj
OSD becomes a bit unresponsive in visual feedback when the player is paused because it paints at a lower rate, but there's nothing that can be done about it at the moment.
Also it'd be nice if we could disable the internal OSD for MPDN as it stack ups right now.
Right now it:
* Shows the currently playing filename
* Playtime & duration
* If we have a file with chapters, it'll also show what chapter we're on
* Giant button to close the player
* Previous and next buttons for controlling your playlist
I'd also like to make this responsive (e.g. bigger fonts on bigger screens) later.
> Add an on-screen display

- Extensions/PlayerExtensions/OnScreenDisplay.ConfigDialog.Designer.cs
- Extensions/PlayerExtensions/OnScreenDisplay.ConfigDialog.cs
- Extensions/PlayerExtensions/OnScreenDisplay.cs
- Mpdn.Extensions.csproj
The OSD always stayed on-screen because the `MouseMove` event keeps firing if the pointer is visible on the frame even if you don't move your mouse. This fixes that issue. I've also added the ability to enable or disable the OSD through the settings. By default it is disabled.
~~I also tried to make this not dependent on the Playlist, but apparently a lot of extensions rely on it, so I guess it doesn't really matter.~~ (Nvm, its out of scope for this PR)
> Minor fixup and add OSD config settings

- Extensions/PlayerExtensions/PlaylistForm.cs
- The Playlist RemoveFile method stops media playback if the last item in the playlist is removed. This should not occur, playback should instead stop if the removed item is the currently playing file from the playlist (this logic is invoked by the RemoteControl extension, not the playlist itself)
> Fix incorrect RemoveFile method
